// frontend-cli/src/app/vote/bar/bar.component.ts
import { Component, OnInit, Input} from '@angular/core';
import { Bar} from '../../baselineBar';


@Component({
  selector: 'vote-bar',
  templateUrl: './bar.component.html',
  styleUrls: ['./bar.component.css']
})
export class BarComponent implements OnInit {

  constructor() { }

  percentageBase: number = 5;
  percentageDelta: number = 5;
  absoluteDelta: number = 0;
  stepping: number = 5000;

  increaseBar() {
      this.absoluteDelta = this.absoluteDelta + this.stepping; 
      this.updateBar();       
  }  

  decreaseBar() {
      this.absoluteDelta = this.absoluteDelta - this.stepping;  
      this.updateBar();      
  }    

  updateBar(){
    this.percentageDelta = this.absoluteDelta / 1000;
  }

  ngOnInit() {
    const absoluteBase = this.bar.basevalue;
    this.percentageBase = absoluteBase / 1000;
    this.absoluteDelta = this.bar.basevalue + (this.bar.delta || 0);
    this.updateBar();   
  }

  @Input()
  bar:  Bar;

}


    <div>
      {{bar.category}} - {{bar.basevalue}} Mio. Euro
      <md-progress-bar mode="determinate" value="{{percentageBase}}"></md-progress-bar>
      <p>Mein Vorschlag: {{absoluteDelta}} Mio. Euro</p>
      <md-progress-bar mode="determinate" value="{{percentageDelta}}"></md-progress-bar>      
      <br>
      <button md-button (click)="increaseBar()">PLUS 5 MILLIARDEN</button>
      <button md-button (click)="decreaseBar()">MINUS 5 MILLIARDEN</button>
      <br>
    </div>
    <br>

// frontend-react/app/voteview/Bar.jsx
import React from "react";
import mui from "material-ui";

import {Card, CardTitle, CardText} from 'material-ui/Card';
import LinearProgress from 'material-ui/LinearProgress';
import FlatButton from 'material-ui/FlatButton';

const Bar = React.createClass({
    render() {
      const absoluteBase = this.props.basevalue;
      const percentageBase = absoluteBase / 1000;
      const absoluteDelta = this.props.basevalue + (this.props.delta || 0);
      const percentageDelta = absoluteDelta / 1000;
      return (
          <div key={this.props.basevalueId}>
             <p>{this.props.category} - {this.props.basevalue} Mio. Euro</p>
             <LinearProgress mode="determinate" value={percentageBase} />
             <p>Mein Vorschlag: {absoluteDelta} Mio. Euro</p>
             <LinearProgress mode="determinate" value={percentageDelta} />
             <FlatButton label="minus 5 milliarden" primary={true} onClick={this.props.onSetDelta.bind(null, this.props.basevalueId, (this.props.delta || 0) - 5000)} />
             <FlatButton label="plus 5 milliarden" primary={true} onClick={this.props.onSetDelta.bind(null, this.props.basevalueId, (this.props.delta || 0) + 5000)} />
          </div>
      );
    }
});

module.exports = Bar;
